name: CI/CD for Angular Front-End

on:
  push:
    branches: [ frontOff ]

jobs:
 
  CI:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

     
     
      - name: Build Docker image
        run: docker build -t frontoff-img:${{ github.sha }} .
      - name: Verify image build
        run: docker images
     # - name: Tag image for latest deployment (optional)
     #   run: docker tag frontoff-img:${{ github.sha }} frontoff-img:latest

 
  # CD: 
  #   runs-on: self-hosted
  #   needs: CI
  
  #   steps:
  #     - name: Login to Docker Hub (requires secret)
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
     
    #  - name: Push image to Docker Hub
      #  run: docker push chetouiiftikhar/frontoff-img:latest
